[project]
name = "nelli-getting-started"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
nb = "jupyter lab"
demo = "bash scripts/demo_all.sh"

[dependencies]
python = "3.11.*"
pandas = "==2.3.3"
polars = "==1.34.0"
seaborn = "==0.13.2"
scikit-learn = "==1.7.2"
jupyterlab = "==4.4.9"
biopython = "==1.85"

# bio cli
spades = "==4.2.0"
metabat2 = "==2.18"
semibin = "==2.2.0"
mmseqs2 = "==17.b804f"
cd-hit = "==4.8.1"
diamond = "==2.1.13"
mafft = "==7.525"
trimal = "==1.5.0"
iqtree = "==3.0.1"
fasttree = "==2.2.0"
taxonkit = "==0.20.0"
